---
apiVersion: v1
kind: Pod
metadata:
  name: joip44
spec:
  containers:
    - name: jaya
      image: jayaprakashjnks/spc:2.0
      ports:
        - containerPort: 8080
      args:
        - sleep
        - 100000000s  