apiVersion: batch/v1
kind: CronJob
metadata:
  name: cornjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    metadata:
      name: cornjob
    spec:
      backoffLimit: 3
      template:
        metadata:
          name: livedatapod
        spec:
          restartPolicy: OnFailure
          containers:
            - name: alpine
              image: alpine
              args:
                - sleep
                - 10s