
apiVersion: batch/v1
kind: Job
metadata: 
  name: jobpod
spec:
  backoffLimit: 5
  template:
    metadata:
      name: podjob
  spec:
    restartPolicy: OnFailure
    containers:
      - name: alpine
        image: alpine
        args:
          - sleep
          - 1d    
