apiVersion: v1
kind: Pod
metadata:
  name: jaya3
spec:
  containers:
    - name: jenkins/jenkins
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
      args:
        - sleep
        - 1000s
