apiVersion: v1
kind: Pod
metadata:
  name: jaya
spec:
  containers:
    - name: jenkins/jenkins
      image: jenkins/jenkins
      ports:
       - containerPort: 8080
        args:
          - sleep
          - 1d 
